# Generated by Django 3.0.5 on 2020-04-29 11:16

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('titre', models.BooleanField()),
                ('description', models.BooleanField()),
                ('date', models.BooleanField()),
                ('source', models.BooleanField()),
                ('video', models.BooleanField()),
            ],
            options={
                'verbose_name': 'categorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('source', models.URLField(max_length=50)),
                ('video', models.CharField(max_length=200, null=True)),
                ('datePublication', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENIVeille.Categorie')),
            ],
            options={
                'verbose_name': 'publication',
                'ordering': ['datePublication'],
            },
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('wiki', models.URLField(max_length=50)),
            ],
            options={
                'verbose_name': 'technologie',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('lienAvatar', models.CharField(max_length=520)),
                ('mailOublie', models.DateField(null=True)),
                ('abonnement', models.ManyToManyField(related_name='abonné', to='ENIVeille.Technologie')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('moderation', models.ManyToManyField(related_name='moderateur', to='ENIVeille.Technologie')),
                ('sauvegarde', models.ManyToManyField(to='ENIVeille.Publication')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='technologie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENIVeille.Technologie'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='technologie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENIVeille.Technologie'),
        ),
    ]
