# Generated by Django 3.0.5 on 2020-04-15 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motDePasse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('lienAvatar', models.CharField(max_length=520)),
                ('pseudo', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('mailValidation', models.DateField(default=django.utils.timezone.now)),
                ('mailOublie', models.DateField(null=True)),
                ('actif', models.BooleanField(default=False)),
                ('administrateur', models.BooleanField(default=False)),
            ],
        ),
    ]
