# Generated by Django 3.0.5 on 2020-04-21 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('titre', models.BooleanField()),
                ('description', models.BooleanField()),
                ('date', models.BooleanField()),
                ('source', models.BooleanField()),
                ('video', models.BooleanField()),
            ],
            options={
                'verbose_name': 'categorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('wiki', models.URLField(max_length=50)),
            ],
            options={
                'verbose_name': 'technologie',
                'ordering': ['titre'],
            },
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['nom'], 'verbose_name': 'utilisateur'},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='motDePasse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='pseudo',
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('source', models.URLField(max_length=50)),
                ('video', models.CharField(max_length=200, null=True)),
                ('datePublication', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENIVeille.Categorie')),
                ('technologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENIVeille.Technologie')),
            ],
            options={
                'verbose_name': 'publication',
                'ordering': ['datePublication'],
            },
        ),
        migrations.AddField(
            model_name='categorie',
            name='technologie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENIVeille.Technologie'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='abonnement',
            field=models.ManyToManyField(related_name='abonné', to='ENIVeille.Technologie'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='moderation',
            field=models.ManyToManyField(related_name='moderateur', to='ENIVeille.Technologie'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sauvegarde',
            field=models.ManyToManyField(to='ENIVeille.Publication'),
        ),
    ]
