# Generated by Django 3.0.5 on 2020-04-21 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ENIVeille', '0002_auto_20200421_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lienAvatar', models.CharField(max_length=520)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('mailValidation', models.DateField(default=django.utils.timezone.now)),
                ('mailOublie', models.DateField(null=True)),
                ('actif', models.BooleanField(default=False)),
                ('administrateur', models.BooleanField(default=False)),
                ('abonnement', models.ManyToManyField(related_name='abonné', to='ENIVeille.Technologie')),
                ('moderation', models.ManyToManyField(related_name='moderateur', to='ENIVeille.Technologie')),
                ('sauvegarde', models.ManyToManyField(to='ENIVeille.Publication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'utilisateur',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
