# Generated by Django 3.0.5 on 2020-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0003_auto_20200506_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
