# Generated by Django 3.0.5 on 2020-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0003_auto_20200421_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['user'], 'verbose_name': 'utilisateur'},
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='prenom',
        ),
    ]
