# Generated by Django 3.0.6 on 2020-06-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0004_auto_20200506_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-datePublication'], 'verbose_name': 'publication'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='titre',
            field=models.BooleanField(unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contenu',
            field=models.TextField(default='Lorem ipsum fecisse de quis amici amicitia excusatio rem ut excusatio oporteat in ut longe prospicere turpes de spatio prospicere Fanni curriculoque se loco longe aliquantum consuetudo consuetudo in eo sanciatur publicam contra nec Etenim ut causa rei quis est casus causa Deflexit amici in loco rogati contra nos turpes consuetudo Scaevola Etenim neque excusatio amici nec prospicere faciamus enim minime cum fateatur in spatio in longe Turpis cum cum Scaevola loco cum est et igitur nos amici maiorum Etenim rei sanciatur futuros nos se curriculoque futuros res aliquantum minime res nec peccatis aliquantum peccatis eo locati neque prospicere de in.', max_length=12000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
