# Generated by Django 3.0.5 on 2020-04-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0004_auto_20200428_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='administrateur',
        ),
    ]
