# Generated by Django 3.0.5 on 2020-04-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0005_auto_20200428_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='mailValidation',
        ),
    ]
