# Generated by Django 3.0.6 on 2020-06-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0005_auto_20200618_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='titre',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='technologie',
            name='titre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
