# Generated by Django 3.0.6 on 2020-06-18 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENIVeille', '0007_auto_20200618_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
